webapp_restuarant/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Profile

app_name = "user"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="user/login.html", redirect_authenticated_user=True
        ),
        name="Login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/login.html"),
        name="Logout",
    ),
    path(
        "logout/",
        auth_views.PasswordResetDoneView.as_view(template_name="user/login.html"),
        name="PassowrdReset",
    ),
    path("profile/", Profile.as_view(), name="Profile"),
]

webapp_restuarant/webapp_restuarant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
        path("", include("pages.urls")),
        path("user/", include("user.urls")),
        path("restaurant/", include("restaurant.urls")),
        path("order/", include("order.urls")),
        path("deliver/", include("deliver.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

webapp_restuarant/pages/templates/prelogin/index.html
{% load static %}
<!DOCTYPE html >
<html lang="en" dir="rtl">
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>سفارش غذا</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    <link href="{% static 'fav.ico' %}" rel="icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="{% static 'prelogin/assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'prelogin/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{% static 'prelogin/assets/css/style.css' %}" rel="stylesheet">
    <!-- =======================================================
  * Template Name: Restaurantly - v3.6.0
  * Template URL: https://bootstrapmade.com/restaurantly-restaurant-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  </head>
  <body>
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">
      <div class="container position-relative text-center text-lg-start"
           data-aos="zoom-in"
           data-aos-delay="100">
        <div class="row">
          <div class="col-lg-8">
            <h1>
              خوش آمدید <span></span>
            </h1>
            <h2>سامانه‌ی سفارش غذای اینترنتی</h2>
            <div class="btns">
              <a href="{% url 'user:Login' %}"
                 class="btn-menu animated fadeInUp scrollto">ورود</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Hero -->
    <!-- Vendor JS Files -->
    <script src="{% static 'prelogin/assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'prelogin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Template Main JS File -->
    <script src="{% static 'prelogin/assets/js/main.js' %}"></script>
  </body>
</html>