webapp_restuarant/restaurant/urls.py
from django.urls import path
from .views import Checkout, List, Menu

app_name = "restaurant"

urlpatterns = [
    path("checkout/", Checkout.as_view(), name="Checkout"),
    # List all restaurants
    path("list/", List.as_view(), name="Index"),
    #
    path("list/menu/<int:pk>", Menu.as_view(), name="Menu"),
]

webapp_restuarant/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Profile

app_name = "user"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="user/login.html", redirect_authenticated_user=True
        ),
        name="Login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/login.html"),
        name="Logout",
    ),
    path(
        "logout/",
        auth_views.PasswordResetDoneView.as_view(template_name="user/login.html"),
        name="PassowrdReset",
    ),
    path("profile/", Profile.as_view(), name="Profile"),
]

webapp_restuarant/webapp_restuarant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
        path("", include("pages.urls")),
        path("user/", include("user.urls")),
        path("restaurant/", include("restaurant.urls")),
        path("order/", include("order.urls")),
        path("deliver/", include("deliver.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

webapp_restuarant/templates/base/base.html
<!DOCTYPE html>
<html lang="fa">
{% include 'base/head.html' %}

<body oncontextmenu="return false;">

	{% include 'base/header.html' %}

	{% block content %}

	{% endblock content %}

	{% include 'base/footer.html' %}

	{% include 'base/scripts.html' %}

</body>

</html>

webapp_restuarant/templates/base/footer.html
<footer class="footer">
  <div class="subscribe-now line">
    <div class="container">
      <div class="row justify-content-between">
        <div class="col-lg-5 col-md-6">
        </div>

      </div>
    </div>
  </div>
  <div class="container">

  </div>
  <div class="privacy-cards">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="privacy-terms text-center">
            <ul>
              <li><a href="{% url 'restaurant:Index' %}">انتخاب رستوران</a></li>
              <li><a href="{% url 'user:Profile' %}">پروفایل</a></li>
              <li><a href="{% url 'user:Profile' %}#my-orders-btn">سفارش های من</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

</footer>

webapp_restuarant/templates/base/head.html
{% load static %}
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Favicon -->
	<link href="{% static 'fav.ico' %}" rel="shortcut icon" type="image/x-icon" />
	<title>سفارش غذا</title>
	<!-- Bootstrap core CSS-->
	<link href="{% static 'user/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'user/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'user/css/responsive.css' %}" rel="stylesheet">
	<link href="{% static 'user/css/mega.menu.css' %}" rel="stylesheet">
	<link href="{% static 'user/css/owlslider.css' %}" rel="stylesheet">

	<!-- Fontawesome styles for this template-->
	<link href="{% static 'user/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'user/js/toastr/toastr.min.css' %}" rel="stylesheet" type="text/css">
	<script src="{% static 'user/vendor/jquery/jquery.min.js' %}"></script>
</head>

webapp_restuarant/templates/base/header.html
<!--header start-->
<header id="header" class="default">
  <div class="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="topbar-right text-center text-md-right">
            <ul class="list-inline">
              {% if request.user.profile.is_special_type %}
                <li>
                  <a href="{{ request.user.profile.get_special_url }}"><i class="fas"></i>{{ request.user.profile.get_special_string }}</a>
                </li>
              {% endif %}
              <li>
                <a href="{% url 'restaurant:Index' %}"><i class="far fa-notes"></i>خوش آمدید {{ request.user.get_full_name }}</a>
              </li>
              <li>
                <a href="{% url 'user:Profile' %}#my-orders-btn"><i class="far fa-calendar-alt"></i>لیست سفارش ها</a>
              </li>
              <li>
                <a href="{% url 'restaurant:Checkout' %}"><i class="fas fa-shopping-cart"></i>سبد خرید</a>
              </li>

              <li class="nav-item dropdown">
                <a class="dropdown-toggle-no-caret"
                   href="#"
                   id="accountDropdown"
                   role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true"
                   aria-expanded="false"><i class="fas fa-user-circle"></i>حساب کاربری <i class="fas fa-caret-down"></i></a>
                <div class="dropdown-menu dropdown-menu-right"
                     aria-labelledby="accountDropdown">
                  <a class="dropdown-item" href="{% url 'user:Profile' %}">سفارش های من</a>
                  <a class="dropdown-item" href="{% url 'user:Profile' %}#my-orders">لیست سفارش</a>
                  <a class="dropdown-item" href="{% url 'user:Profile' %}#edit-profile">تنظیمات کاربری</a>
                  <a class="dropdown-item" href="{% url 'user:Logout' %}">خروج</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

webapp_restuarant/templates/base/scripts.html
{% load static %}
<!--Core plugin JavaScript-->
{% comment %} <script src="{% static 'user/vendor/jquery/jquery.min.js' %}"></script> {% endcomment %}
<script src="{% static 'user/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'user/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'user/js/owlslider.js' %}"></script>
<script src="{% static 'user/js/toastr/toastr.min.js' %}"></script>
<script>
    function numberWithCommas(x) {
            return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }
    $( document ).ready(function() {

       let hash=$(location).attr('hash');
       if (hash.trim()!=""){
           $("[href='"+hash+"']").trigger( "click");
       }
       {% if messages %}
            {% for message in messages %}
                {% if message.tags %}                    toastr.{{message.tags}}('{{ message }}', '', {timeOut: 5000}){% endif %}
            {% endfor %}
        {% endif %}
    });
</script>