webapp_restuarant/deliver/urls.py
from django.urls import path
from .views import Index, Detail

app_name = "deliver"

urlpatterns = [
    path(
        "",
        Index.as_view(),
        name="Index",
    ),
    path(
        "details/<int:pk>",
        Detail.as_view(),
        name="Detail",
    ),
]

webapp_restuarant/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Profile

app_name = "user"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="user/login.html", redirect_authenticated_user=True
        ),
        name="Login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/login.html"),
        name="Logout",
    ),
    path(
        "logout/",
        auth_views.PasswordResetDoneView.as_view(template_name="user/login.html"),
        name="PassowrdReset",
    ),
    path("profile/", Profile.as_view(), name="Profile"),
]

webapp_restuarant/webapp_restuarant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
        path("", include("pages.urls")),
        path("user/", include("user.urls")),
        path("restaurant/", include("restaurant.urls")),
        path("order/", include("order.urls")),
        path("deliver/", include("deliver.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

webapp_restuarant/deliver/models.py
from datetime import datetime
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

# Create your models here.
class Deliver(models.Model):
    """_summary_
    Whene a Food wants to be deliverd this model holds the info
    """

    INWAY = "inway"
    WAIT_FOR_READY = "wating_for_ready"
    PICKUP = "pickup"
    DELIVERD = "deliverd"
    NDELIVERD = "ndeliverd"
    STATUS_TYPE = [
        (INWAY, "در راه"),
        (PICKUP, "در حال دریافت از رستوران"),
        (DELIVERD, "تحویل داده شده"),
        (NDELIVERD, "تحویل داده نشده"),
        (WAIT_FOR_READY, "در انتظار آماده سازی"),
    ]
    driver = models.ForeignKey("restaurant.driver", on_delete=models.CASCADE)
    order = models.ForeignKey(
        "order.Order", on_delete=models.CASCADE, related_name="deliver"
    )
    start_time = models.DateTimeField(
        auto_now_add=True, auto_now=False, null=True, blank=True
    )
    end_time = models.DateTimeField(
        auto_now=False, auto_now_add=False, null=True, blank=True
    )
    status = models.CharField(max_length=20, choices=STATUS_TYPE)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return " | ".join(
            [self.get_status, self.driver.full_name, self.order.user.full_name]
        )

    @property
    def time_total(self):
        "Calculate time left to deliver"
        return self.end_time - self.start_time

    @property
    def get_status(self):
        status_dict = dict(self.STATUS_TYPE)
        return status_dict[self.status]

    @property
    def get_time_diffrence(self):
        if self.status in [Deliver.PICKUP, Deliver.INWAY]:
            return int((datetime.now() - self.start_time).seconds / 60)

    # def clean(self) -> None:
    #     if self.order:
    #         if self.order.receive_type not in [Order.DELIVER]:
    #             raise ValidationError({"order": "Selected Order is TAKEOUT"})
    #         if self.order.status not in [Order.DELIVERED, Order.DELIVERY]:
    #             raise ValidationError(
    #                 {"order": "Selected Order must be in delivery Status ord Delivered"}
    #             )
    #     return super().clean()

webapp_restuarant/deliver/views.py
from datetime import datetime
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.contrib import messages

from order.models import Order
from .models import Deliver


# Create your views here.
class Index(ListView):
    template_name = "deliver/index.html"
    model = Deliver
    context_object_name = "delivers"

    def get_queryset(self):
        return Deliver.objects.filter(
            driver__user=self.request.user,
            status__in=[Deliver.INWAY, Deliver.PICKUP],
        )


class Detail(DetailView):
    template_name = "deliver/detail.html"
    context_object_name = "order"
    model = Deliver

    def get_object(self):
        deliver = get_object_or_404(Deliver, pk=self.kwargs["pk"])
        return deliver.order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["deliver"] = get_object_or_404(Deliver, pk=self.kwargs["pk"])
        return context

    def post(self, request, pk):
        deliver = get_object_or_404(Deliver, pk=pk)
        if "action" in request.POST and "description" in request.POST:
            if request.POST["action"] == "delivered":
                deliver.status = Deliver.DELIVERD
                deliver.description = request.POST["description"]
                deliver.order.status = Order.DELIVERED
                deliver.end_time = datetime.now()
                deliver.save()
                deliver.order.save()
                messages.success(
                    request,
                    "با موفقیت ثبت شد",
                )
                return JsonResponse(
                    {"response": "success", "redirect": reverse_lazy("deliver:Index")}
                )
            else:
                if len(request.POST["description"]) < 15:
                    return JsonResponse(
                        {
                            "response": "error",
                            "error": "حداقل توضیحات برای تحویل ندادن سفارش باید ۱۵ حرف باشد",
                        }
                    )
                deliver.status = Deliver.NDELIVERD
                deliver.description = request.POST["description"]
                deliver.order.status = Order.FAILED
                deliver.save()
                deliver.order.save()
                messages.warning(
                    request,
                    "تحویل داده نشدن سفارش ثبت شد.لطفا هرچه سریع تر با رستوران تماس بگیرید",
                )
                return JsonResponse(
                    {"response": "success", "redirect": reverse_lazy("deliver:Index")}
                )
        else:
            return Http404

webapp_restuarant/deliver/templates/deliver/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    {% csrf_token %}
    <section class="bill-slip">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-6 col-12">
                    {% include 'order/order_bil.html' %}
                    <div class="m-2 float-right">
                        <div class="hide" id="textInput">
                            <input class="video-form m-2"
                                   type="text"
                                   placeholder="توضیحات را اینجا وارد کنید"
                                   id="txt_description"/>
                        </div>
                        <div class="m-2">
                            <a href="tel:{{ order.user.profile.phone }}" class="btn btn-info">تماس با تحویل گیرنده</a>
                            <button class="btn btn-primary"
                                    data-toggle="modal"
                                    data-id="deliverd"
                                    data-target="#trace"
                                    onclick="onButtonClick2(this);">
                                تحویل داده شد
                            </button>
                            <input class="btn btn-danger"
                                   type="button"
                                   name="answer"
                                   value="تحویل داده نشد"
                                   onclick="onButtonClick2(this);"/>
                        </div>
                        <div class="hide" id="callb">
                            <div class="slip-bill-left">
                                <h5>ضمن ثبت توضیحات لطفا هم اکنون موضوع را با رستوران در میان بگذارید</h5>
                                <p>
                                    {{ order.restaurant.phone }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        function onButtonClick2(sender) {
            let data={};
            data["description"]=$("#txt_description").val();
            if ($(sender).data("id")!="deliverd"){
                data["action"]="ndeliver";
            }
            else{
                data["action"]="delivered";
            }
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            $.ajax({
                headers: {
                    'X-CSRFToken': csrftoken
                },
                type: "POST",
                url: "{% url 'deliver:Detail' deliver.id %}",
                data: data,
                dataType: "json",
                success: function (response) {
                    if (response["response"] == "success") {
                        window.location.href = response["redirect"];
                    } else {
                        toastr.error(response["error"], '', { timeOut: 5000 });
                    }
                }
            });
        }
    </script>
{% endblock content %}

webapp_restuarant/deliver/templates/deliver/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <!--title-bar start-->
    <section class="title-bar text-center" style="min-height: 850px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="left-title-text">
                        <h3>پنل پیک</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--title-bar end-->
    <!--bill-slip start-->
    {% for deliver in delivers %}
        <section class="bill-slip">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6 col-md-6 col-12">
                        <div class="card text-center mmaman">
                            <div class="card-header">{{ deliver.order.id }}</div>
                            <div class="card-body">
                                <h5 class="card-title">{{ deliver.order.user.full_name }}</h5>
                                <p class="card-text">
                                    {{ deliver.order.address }}
                                </p>
                                <a href="tel:{{ deliver.order.user.profile.phone }}"
                                   class="btn btn-info">تماس با تحویل گیرنده</a>
                                <a href="{% url 'deliver:Detail' deliver.id %}" class="btn btn-primary">مشاهده</a>
                            </div>
                            <div class="card-footer text-muted">{{ deliver.get_time_diffrence }} دقیقه پیش</div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endfor %}
{% endblock content %}